# -*- coding: utf-8 -*-

# Output of time.mktime(datetime.max.timetuple()) on macOS
# This value must be hardcoded for compatibility with Windows
# Platform-independent max timestamps are hard to form
# https://stackoverflow.com/q/46133223
MAX_TIMESTAMP = 253402318799.0
MAX_TIMESTAMP_MS = MAX_TIMESTAMP * 1000
MAX_TIMESTAMP_US = MAX_TIMESTAMP * 1000000

NUM_SECONDS_IN_A_MINUTE = 60
NUM_MINUTES_IN_AN_HOUR = 60
NUM_HOURS_IN_A_DAY = 24
NUM_DAYS_IN_A_WEEK = 7
NUM_WEEKS_IN_A_MONTH = 4
NUM_MONTHS_IN_A_YEAR = 12

# Humanize bounds
# TODO: compress the constants
BOUND_NOW = 10
BOUND_SEC = NUM_SECONDS_IN_A_MINUTE
BOUND_MIN_SINGULAR = NUM_SECONDS_IN_A_MINUTE * 2
BOUND_MIN_PLURAL = NUM_SECONDS_IN_A_MINUTE * NUM_MINUTES_IN_AN_HOUR
BOUND_HOUR_SINGULAR = NUM_SECONDS_IN_A_MINUTE * NUM_MINUTES_IN_AN_HOUR * 2
BOUND_HOUR_PLURAL = (
    NUM_SECONDS_IN_A_MINUTE * NUM_MINUTES_IN_AN_HOUR * NUM_HOURS_IN_A_DAY
)
BOUND_DAY_SINGULAR = (
    NUM_SECONDS_IN_A_MINUTE * NUM_MINUTES_IN_AN_HOUR * NUM_HOURS_IN_A_DAY * 2
)
BOUND_DAY_PLURAL = (
    NUM_SECONDS_IN_A_MINUTE
    * NUM_MINUTES_IN_AN_HOUR
    * NUM_HOURS_IN_A_DAY
    * NUM_DAYS_IN_A_WEEK
)
BOUND_WEEK_SINGULAR = (
    NUM_SECONDS_IN_A_MINUTE
    * NUM_MINUTES_IN_AN_HOUR
    * NUM_HOURS_IN_A_DAY
    * NUM_DAYS_IN_A_WEEK
    * 2
)
BOUND_WEEK_PLURAL = (
    NUM_SECONDS_IN_A_MINUTE
    * NUM_MINUTES_IN_AN_HOUR
    * NUM_HOURS_IN_A_DAY
    * NUM_DAYS_IN_A_WEEK
    * NUM_WEEKS_IN_A_MONTH
)
BOUND_MONTH_SINGULAR = BOUND_WEEK_PLURAL * 2
BOUND_MONTH_PLURAL = BOUND_WEEK_PLURAL * NUM_MONTHS_IN_A_YEAR
BOUND_YEAR_SINGULAR = BOUND_MONTH_PLURAL * 2
