language: python
python:
  - "3.8"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - pre-commit install
script:
  - pytest
  - pytest tests/test_arrow.py::TestTestArrowFactory::test_fromordinal
  - pytest tests/test_util.py::TestUtil::test_validate_ordinal
  - pytest tests/test_arrow.py::TestArrowDatetimeInterface::test_isoformat_timespec
