language: python
python:
  - "3.8"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - pre-commit install
script:
  - pytest
  - pre-commit run --all-files --show-diff-on-failure
